---
- name: Update certificates on OpenShift
  hosts: localhost
  connection: local
#  vars_files:
#    - "/usr/local/src/littleorchardpreschool-ansible/vaults/{{ VAULT_ID }}/vault"
  roles:
    - update_certificates
